apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/monitoring-team
  - ../base/dev-team
patches:
  - path: monitoring-team-patch.yaml
  - path: dev-team-patch.yaml
